### ISSUE TITLE
Error in _zephir_call_user_function in ZendEngine3 fcall.c

### ISSUE THREAD

**Issue by SerafimArts** [zephir-lang/zephir#1202] opened 2016-03-07 07:53 UTC
Environment:
1) php 7.0 x86 nts
1.1) Trying with TS too
2) VS 2015 (version 14.0)
3) Zephir v0.8
3.1) Trying with master branch too
4) Windows 7 x64

Code:

```
namespace App;

class Version
{
    public static function get()
    {
        return "0.0.1 super beta";
    }
}
```

Then run `zephir compile`:

```
...>zephir compile
Copying new kernel files...
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
```

No errors but has compile.log:

```
"Cl.exe" / FI main blah blah blah...
...
object.c
operators.c
require.c
string.c
D:\Projects\Morph\bin\ext\kernel\object.c (65): warning C4090: dgЄzhЁp: a §lҐ Єў "ЁdЁЄ v®al" const "
time.c
variables.c
"Cl.exe" /... blah blah blah ...

Microsoft (R) Windows (R) Resource Compiler Version 10.0.10011.16384
Copyright (C) Microsoft Corporation. All rights reserved.

D:\Projects\Morph\bin\ext\Release\array.obj: warning LNK4042: Set the object more than once; excess are not counted
D:\Projects\Morph\bin\ext\Release\fcall.obj: warning LNK4042: Set the object more than once; excess are not counted
   Create a library D:\Projects\Morph\bin\ext\Release\php_app.lib and object D:\Projects\Morph\bin\ext\Release\php_app.exp
fcall.obj: error LNK2019: unresolved external reference to the symbol in _zephir_call_function_opt _zephir_call_user_function function
D:\Projects\Morph\bin\ext\Release\php_app.dll: fatal error LNK1120: unresolved external elements: 1
```

And only php_app.dll.manifest and php_app.dll.res in Release dir, no binaries
='(

**Comment by SerafimArts** [comment] 2016-03-07 22:10
I trying to build extension over **clear** virtual machine:
1) Windows 10 x64 Enterprise 2015 LTSB
2) Zephir release snapshot v0.8
3) PHP 7.0.4 Non Thread Safe x86
4) PHP 7 (x86) develpack from http://windows.php.net/downloads/releases and php 7 sdk from http://windows.php.net/downloads/php-sdk/ (with binary tools copied inside sdk path)
5) VisualStudio 2015 Express with C++ support and Extensibility tools update 1

And i have this error again:
![image](https://cloud.githubusercontent.com/assets/2461257/13585052/88066c6e-e4ca-11e5-9cbd-cfb960d59f26.png)

Steps:
- Install VS2015
- Restart PC
- Open Dev Console and running `.\Microsoft Visual Studio 14.0\VC\vcvarsall.bat`
- Download PHP 7.0.4 x86 nts to `C:\php7\..`
- Add to PATH variable
- Download php sdk to `C:\php7sdk`
- Downalod php sdk binary tools to `C:\php7sdk`
- Add `C:\php7sdk\bin` to PATH variable
- Download php 7 devel pack to `C:\php7devpack` 
- Add `PHP_SDK_SCRIPT_PATH`, `PHP_SDK_BIN_PATH`, `PHP_SDK_PATH` and `BISON_SIMPLE` variables (see screenshot)
- Download zephir 0.8 to `C:\zephir`
- Add `C:\zephir\bin` to PATH
- Create a simple zephir app
- Open VS Dev Console and run `zephir build`

**Comment by SerafimArts** [comment] 2016-03-07 22:35
If i remove this to lines:
![image](https://cloud.githubusercontent.com/assets/2461257/13585617/d952cc2c-e4cd-11e5-86c9-16f1b78cc210.png)

Building are finished successfully! :dancers: I dont know what this means (because i don know C++ like a pro), but... Jedi Driven Development...

**Comment by steffengy** [comment] 2016-03-09 21:13
I'm not really having an idea what's causing that failure on your end.
From the symptoms it seems like extended/fcall.c is not compiled.
(Your file changes above are not recommended, that will simply prevent most function calls from working)

Does the file `fcall.c` in `ext/kernel/` exist?
Is there a line like `ADD_SOURCES(... + "/kernel/extended", "array.c fcall.c",")` in config.w32?

**Comment by Jurigag** [comment] 2016-03-19 19:48
Sholdn't we use:
zephir build --backend=ZendEngine3
for php 7 ? Or zephir already figure it out ? Beacause in phalcon you have to use it to compile 2.1.x for php7.

**Comment by steffengy** [comment] 2016-03-19 19:57
You only need to specify a backend if it differs from the PHP version running zephir.

**Comment by sergeyklay** [comment] 2016-03-19 20:25
And use `master` branch :)

**Comment by Jurigag** [comment] 2016-03-19 21:49
> Trying with master branch too

**Comment by wxmaper** [comment] 2016-04-03 07:43
This error becouse sources have duplicates: **zephir-master\kernels\ZendEngine3\fcall.c** and **zephir-master\kernels\ZendEngine3\extended\fcall.c**. Its creating one **.obj** file named as **fcall.obj**

> NMAKE : warning U4004: too many rules for target 'ext\Release_TS\fcall.obj'
> NMAKE : fatal error U1077...

I'm rename _zephir-master\kernels\ZendEngine3\extended\_**fcall.c** and _zephir-master\kernels\ZendEngine3\extended\_**array.c** to 
_zephir-master\kernels\ZendEngine3\extended\_**efcall.c** and _zephir-master\kernels\ZendEngine3\extended\_**earray.c**

and has made changes to a two files:
**templates\ZendEngine3\config.m4** at line 12
**and templates\ZendEngine3\config.w32** at line 6
(rename extended\fcall.c to extended\efcall.c etc.)

**Comment by steffengy** [comment] 2016-04-04 15:21
cannot reproduce that now.
An x64 extension for PHP7 builds flawlessy here.
should be fixed therefore.

**Closed as completed by steffengy** 2016-04-04 15:21 UTC
