### ISSUE TITLE
Certain method calls fail when called from static context and compiled with "internal-call-transformation": true

### ISSUE THREAD

**Issue by andrewdalpino** [zephir-lang/zephir#2005] opened 2019-11-09 22:59 UTC
I get the following errors when running this [test](https://github.com/RubixML/Tensor/blob/master/tests/MatrixTest.php) with the extension compiled with `internal-call-transformation: true`. The errors go away if we disable the optimization.

```sh
1) Tensor\Tests\MatrixTest::test_inverse
RuntimeException: Trying to call method m on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:403

2) Tensor\Tests\MatrixTest::test_det
RuntimeException: Trying to call method m on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:417

3) Tensor\Tests\MatrixTest::test_rank
RuntimeException: Trying to call method m on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:458

4) Tensor\Tests\MatrixTest::test_full_rank
RuntimeException: Trying to call method m on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:465

5) Tensor\Tests\MatrixTest::test_ref
RuntimeException: Trying to call method m on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:511

6) Tensor\Tests\MatrixTest::test_rref
RuntimeException: Trying to call method m on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:525

7) Tensor\Tests\MatrixTest::test_lu_decomposition
RuntimeException: Trying to call method issquare on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:539

8) Tensor\Tests\MatrixTest::test_cholesky
RuntimeException: Trying to call method issquare on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:571

9) Tensor\Tests\MatrixTest::test_solve
RuntimeException: Trying to call method issquare on a non-object

/mnt/c/Users/User/Workspace/Rubix/Tensor/tests/MatrixTest.php:608
```

At first glance, it appears that we can't access methods on objects from another class' static context. This is similar to https://github.com/phalcon/zephir/issues/2000 but different.

I traced the calls back to the matrix decomposition objects [here](https://github.com/RubixML/Tensor/tree/master/src/Decompositions). They all use static factories. Here is an excerpt from the [LU](https://github.com/RubixML/Tensor/blob/master/src/Decompositions/LU.php) decomposition where one of the errors is being thrown. It's a similar case for each of the other decompositions.

```zephir
/**
     * Factory method to decompose a matrix.
     *
     * @param \Tensor\Matrix a
     * @return self
     */
    public static function decompose(const <Matrix> a) -> <Lu>
    {
        if !a->isSquare() {
            throw new RuntimeException("Cannot decompose a non square matrix.");
        }

        // ...
    }
```

There also seems to be the issue that methods being overloaded by a child class are not being called (the parent method is called instead.) This may or may not be related to this issue - and again, only when compiled with `internal-call-transformation: true`.

**Comment by sergeyklay** [comment] 2019-11-14 06:48
@dreamsxin Could you please take a look?

**Comment by dreamsxin** [comment] 2019-11-14 09:16
Because `ZEPHIR_STATIC_CALL_INTERNAL_METHOD_P` use `ZEPHIR_SET_THIS_EXPLICIT_NULL`.
I will try replace current_execute_data

**Comment by dreamsxin** [comment] 2019-11-14 23:34
Please test again, There's another mistake:
`PHP Warning:  array_reduce() expects parameter 2 to be a valid callback, non-static method Tensor\Matrix::implodeRow() cannot be called statically`
```zephir
    public function __toString() -> string
    {
        return trim(array_reduce(this->a, ["Tensor\\Matrix", "implodeRow"], ""));
    }
```

**Comment by andrewdalpino** [comment] 2019-11-16 20:26
Hi @dreamsxin it looks like the  https://github.com/phalcon/zephir/commit/900bd5f76696805c0a161bed5b0a4626b16258d6 commit to the development branch fixes the primary issue. The issue of overriding parent methods still exists so that probably a separate issue.

Thank you for pointing out the error with `__toString()` (I had forgotten about that). Changing the `implodeRow()` method to static seems to work, however, it may be good to note that this is unnecessary in PHP. I'm not sure the behavior that Zephir intends.

Thanks again for your great work guys

**Comment by sergeyklay** [comment] 2019-11-17 08:02
Closing, this is fixed. Lets follow up in separate issue with the overriding parent methods.

@andrewdalpino Could you please open a new issue with problem description and code to reproduce?

**Closed as completed by sergeyklay** 2019-11-17 08:02 UTC
Labels: bug
