### ISSUE TITLE
BUG:  gc_possible_root

### ISSUE THREAD

**Issue by chrysanthemum** [zephir-lang/zephir#1970] opened 2019-10-13 18:11 UTC
In PHP 7.1.32, This bug occurs.
In PHP 7.2.22, This bug does not occur.

zephir (0.12.9 ) git revision number: f345c4a2dede62b84b68a85b44a924dbe2d4ece8

test/globals/server.zep

```
namespace Test\Globals;

class Server
{
    public function check() {
    	return _SERVER["HTTP_USER_AGENT"];
    }
}
```

manual.php
```
$t = new Test\Globals\Server();
$t->check();
```

output:
```
Assertion failed: ((ref)->gc.u.v.type == 7 || (ref)->gc.u.v.type == 8), function gc_possible_root, file /Users/chrysanth/project/php/php-7.1/Zend/zend_gc.c, line 269.
```

**Comment by chrysanthemum** [comment] 2019-10-13 18:32
@dreamsxin Please help

**Comment by dreamsxin** [comment] 2019-10-14 09:48
I test branch development, cannot reproduce.

PHP 7.1.32-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Sep  2 2019 13:28:17) ( NTS )

**Comment by sergeyklay** [comment] 2019-10-14 10:09
@dreamsxin Use `NTS DEBUG` or `ZTS DEBUG`, not just `NTS`

**Comment by dreamsxin** [comment] 2019-10-14 23:53
Can test change zephir_get_global
```c
if (Z_TYPE_P(gv) == IS_ARRAY) {
				ZVAL_COPY_VALUE(arr, gv);
				zend_string_release(str);
				return SUCCESS;
			}
```
To 
```c
if (Z_TYPE_P(gv) == IS_ARRAY) {
				ZVAL_DUP(arr, gv);
        zend_hash_update(&EG(symbol_table), are, arr);
	zend_string_release(str);
				return SUCCESS;
			}
```

Link https://github.com/phalcon/zephir/issues/1961#issuecomment-541478314

**Comment by dreamsxin** [comment] 2019-10-15 00:33
Or use RETURN_NULL replace RETURN_CTORW

**Comment by sergeyklay** [comment] 2019-10-15 18:52
@dreamsxin It is current implementation

https://github.com/phalcon/zephir/blob/6f6fe1578e2295a42cbc0936010cc0983bc7b7e5/kernels/ZendEngine3/main.c#L102-L110

**Comment by sergeyklay** [comment] 2019-10-15 21:15
Looks like it is fixed in latest Zephir.

```zep
// Zephir code
namespace Bug;

class Globals {

    public function getUserAgent() {
        return _SERVER["HTTP_USER_AGENT"];
    }
}
```

```php
// manual.php
<?php

use Bug\Globals;

$_SERVER["HTTP_USER_AGENT"] = "Test";

$test = new Globals;
echo $test->getUserAgent() . PHP_EOL;
```

Output:
```
Test
```

Tested PHP versions:
- 7.1.30 ( ZTS DEBUG )
- 7.2.20 ( ZTS DEBUG )
- 7.3.7 ( ZTS DEBUG )

Tested Zephir versions:
- 0.12.9 (latest release)
- 0.12.10 (development branch)

If there are bugs, we can follow up in separate issues.

**Closed as completed by sergeyklay** 2019-10-15 21:15 UTC
Labels: bug
