### ISSUE TITLE
I get non-existent warning function for existent function.

### ISSUE THREAD

**Issue by joeyhub** [zephir-lang/zephir#1843] opened 2019-03-26 22:12 UTC
If I have the param <Closure> cb then cb() in that function...

`Warning: Function "cb" does not exist at compile time.`

I'm guessing it's probably trying to call it by name if I run it. Given ->call will break the bind the only thing that seems like it can work is call_user_func.

**Comment by sergeyklay** [comment] 2019-03-28 20:20
Could you please provide the code to reproduce

**Comment by Jurigag** [comment] 2019-04-30 15:45
If this function is defined in php then compiler doesn't know about it until you will import it somehow during compilation.

**Comment by sergeyklay** [comment] 2019-04-30 16:23
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed as completed by sergeyklay** 2019-04-30 16:23 UTC
Labels: need script to reproduce, need information
