### ISSUE TITLE
Adding PHP code import functionality

### ISSUE THREAD

**Issue by erickmajor** [zephir-lang/zephir#1574] opened 2017-08-25 13:55 UTC
I would like to know if there is a possibility to create a PHP code import option for zephir-cli.

In this way it would be easy to adjust PHP libraries for Zephir, in order to facilitate the process of encoding extensions.

Thanks for the attention.

**Comment by sergeyklay** [comment] 2017-08-26 13:59
@erickmajor Which "PHP code import" do you mean? Could you please explain a bit more. Any examples and/or pseudo-code?

**Comment by sergeyklay** [comment] 2017-09-13 11:39
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed as completed by sergeyklay** 2017-09-13 11:39 UTC

**Comment by ninjapanzer** [comment] 2017-09-13 11:52
I believe @erickmajor is asking for a trans-pilation or conversion option. `PHP -> Zephir`

So that an existing PHP lib can be parsed and converted to Zephir automatically. I know I would personally like this functionality.

**Comment by erickmajor** [comment] 2017-09-18 17:00
Hello @sergeyklay and @ninjapanzer,

I apologize for the delay.

That's exactly what the @ninjapanzer said: I would like to get a code written in PHP and convert it to Zephir. In my case, I would like to convert a class with the namespaces feature, since it is mandatory for Zephir functionality.

**Comment by Jurigag** [comment] 2017-09-18 18:10
There are exactly 3rd party projects which do this. The problem is zephir isn't 1:1 php. For example anynomous functions can't be written in zephir easily(we need separated class for it etc). Or there is no use keyword etc. For example there is this - https://github.com/fezfez/php-to-zephir

**Comment by erickmajor** [comment] 2017-09-18 18:32
Thanks for the reply @Jurigag.

Not how to incorporate the @fezfez solution into zephir-cli?

**Comment by Jurigag** [comment] 2017-09-18 18:45
Well we could focus on it some day, yea, but still, it won't be 1:1, not all functionallity will be working, like references or use keyword etc. Those are not possible in zephir atm, so we would need some brilliant workaround cuz i think it's somehow possible to refactor code to not use references or use keyword.
