### ISSUE TITLE
Compiling Zephir on Windows

### ISSUE THREAD

**Issue by amichelins** [zephir-lang/zephir#1282] opened 2016-07-15 23:42 UTC
I install Zephir from composer. But is not running becouse is mising, the parser and Exception

I follow this steps from this url http://blog.benoitblanchon.fr/build-php-extension-on-windows/ And i succefuly copile de parser (phpzephirparser.dll) in Windows 10 x64, with PHP 5.6.23 x64 and VC 11

I am tring to compile de Zephir extension.

But a this time i have this errors :
```
zephir.c(152) : error C2198: 'zephircompileclass' : too few arguments for call
```

```c
if (!memcmp(ZSTRVALP(type), "class", strlen("class") + 1)) 
{
    zephircompileclass( context, z ); # This
}
```

zephir.c(233) : error C2065: 'zendglobalsid' : undeclared identifier

```c
zendzephirglobals *zephirglobalsptr = ZEPHIRT_VGLOBAL; # This
```

How to solve this problems to build Zephir?

Thank in advance

**Comment by amichelins** [comment] 2016-07-15 23:59
I am tring to compile de Zephir extension to solve :

D:\Zephir_ext\sriutl\sriutl>zephir build
Zephir\Exception: Extension namespace cannot be loaded --> this

**Comment by sergeyklay** [comment] 2017-04-06 17:27
@amichelins Could you please provide a bit more code to reproduce.

**Comment by sergeyklay** [comment] 2018-04-16 05:37
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed as completed by sergeyklay** 2018-04-16 05:37 UTC
Labels: need script to reproduce, windows
