### ISSUE TITLE
getting zend_error_noreturn error

### ISSUE THREAD

**Issue by sarwarcse** [zephir-lang/zephir#1534] opened 2017-05-09 12:19 UTC
I am getting this error
---------------------
```
PHP Warning:
PHP Startup:
Unable to load dynamic library '/usr/lib64/php/modules/myapp.so' -
/usr/lib64/php/modules/myapp.so:
undefined symbol: zend_error_noreturn in Unknown on line 0
```

**My code is** 
```zep
namespace Myapp;
class Greeting
{
    public static function test (string abc) {

                return "test back";
    }
}
```

**But everything is ok on this code**
```zep
namespace Myapp;
class Greeting
{
    public static function test () {    //no parameter

                return "test back";
    }
}
```
When i set a parameter of method **test** with **string abc** then I got the error. But I compiled it in windows version it works fine.. 

My server configuration is 
Zephir Version : 0.9.7-edf9433136
Centos 7.3 64bit
PHP 5.6.30 (cli) (built: Jan 19 2017 07:57:06)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies

**Comment by sergeyklay** [comment] 2017-05-09 22:55
@sarwarcse Did you use master or development branch? Could you please provide `zephir version` output

**Comment by sarwarcse** [comment] 2017-05-10 05:19
@sergeyklay , Thanks for your comment. Zephir Version is : 0.9.7-edf9433136.

I really stack now, the same generated .so file worked in another same configuration sever. I have generated this server and worked in another server not this server, I don't know why.

**Comment by sergeyklay** [comment] 2017-05-28 12:14
I'm not sure that this is Zephir issue. At least I managed to test this use case using different versions of PHP (#1543). I'm closing this issue because I can't to reproduce it. Feel free to add any relevant information if you believe that actually there is an issue.

**Closed as completed by sergeyklay** 2017-05-28 12:14 UTC
