### ISSUE TITLE
class properties disappear if assigned a var that has no value assigned

### ISSUE THREAD

**Issue by chilimatic** [zephir-lang/zephir#1618] opened 2017-12-28 10:50 UTC
While I was implementing the transaction feature I notices a curious behaviour that happened in the unittests 

a getter threw an exception that a defined property does not exist. I found my bug but I was curious. I tested if this is a behaviour that can be easily reproduced.

php 7.2 + zephir 1.0.7

2 classes:

TestCase: 
```zephir
namespace Bugreport;

class PropertyIsGoingToDisappear {
    protected _magicProperty;

    public function setProperty(param) {
        let this->_magicProperty = param;

        return this;
    }

    public function getProperty() {
        return this->_magicProperty;
    }
}
```
and
```zephir
namespace Bugreport;

class MyClass {

    protected _property1;

    public function useSetterOfChild() {
        var myValue, instanceToBeReturned;

        let instanceToBeReturned = new PropertyIsGoingToDisappear();
        return instanceToBeReturned->setProperty(myValue);
    }
}

```
invoked by 
```php
$myObject = new Bugreport\MyClass();
$returnedObject = $myObject->useSetterOfChild();

// same as the returned object
$myOtherObject = new Bugreport\PropertyIsGoingToDisappear();
$myOtherObject->setProperty(1);

var_dump($myOtherObject->getProperty());
var_dump($returnedObject->getProperty());
```

results in 
```sh
/home/j/development/repos/bugreport-zephir/test.php:19:
int(1)
PHP Notice:  Undefined property: Bugreport\PropertyIsGoingToDisappear::$_magicProperty in /home/j/development/repos/bugreport-zephir/test.php on line 20
PHP Stack trace:
PHP   1. {main}() /home/j/development/repos/bugreport-zephir/test.php:0
PHP   2. Bugreport\PropertyIsGoingToDisappear->getProperty() /home/j/development/repos/bugreport-zephir/test.php:20
/home/j/development/repos/bugreport-zephir/test.php:20:
NULL
```

the issue is 
```zephir
var myValue, instanceToBeReturned;
instanceToBeReturned->setProperty(myValue);
```

the var has no value assigned so instead of setting a null value it removes the property in runtime, which is a quite curious sideeffect.

**Comment by sergeyklay** [comment] 2019-02-19 21:30
@dreamsxin Another strange issue that seems to have always been. Could you please look at this

**Comment by dreamsxin** [comment] 2019-02-20 05:24
PHP 7.2
Zephir 0.11.10 can't reproduce, it's initialize:
```c
ZVAL_UNDEF(&myValue);
```
@chilimatic You can test again use Zephir 0.11.10

**Comment by sergeyklay** [comment] 2019-10-11 10:37
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises

**Closed as completed by sergeyklay** 2019-10-11 10:37 UTC
Labels: bug, need information
