### ISSUE TITLE
i got a 50mb size dll file

### ISSUE THREAD

**Issue by maybeTomorrow** [zephir-lang/zephir#1568] opened 2017-08-02 11:25 UTC
How do I compress DLL file sizes?

**Comment by sergeyklay** [comment] 2017-08-02 11:40
Please provide steps to reproduce. What exactly happens to get dll

**Comment by maybeTomorrow** [comment] 2017-08-02 12:16
maybe i complier too many files ,about 200+ . but the so file only 8mb in unix 
step1 :zephir generate utils
step2:copy ext to  php source file/ext/utils
step3:configure --disable-all --enable-cli --enable-utils --disable-zts &&nmake

**Comment by sergeyklay** [comment] 2018-04-24 18:28
I want to close this issue because I don't want a bunch of these lying around. I'd like to know what happens on Windows too, but keeping the issue open doesn't answer to question and doesn't determine the real issue (if any). If anyone wants to get started to investigate, I'd love that. I propose to continue this discussion at the specialized forums dedicated to optimizing compilation PHP (and extensions) for Windows. Anyway your question is too abstract.

**Closed as completed by sergeyklay** 2018-04-24 18:28 UTC
Labels: need information
