### ISSUE TITLE
Invalid type argument of unary '*' (have 'zval')

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1126] opened 2015-11-13 11:22 UTC
On the PHP7:

``` zep
protected function stripPadding(string value) -> string
    {
        var pad, len;

        let len = (int) strlen(value),
            pad = (int) ord(value[len - 1]);

        return this->paddingIsValid(pad, value) ? substr(value, 0, len - pad) : value;
    }
```

``` c
PHP_METHOD(Ice_Crypt, stripPadding) {

        unsigned char _0;
        int pad = 0, len = 0, ZEPHIR_LAST_CALL_STATUS;
        zval *value_param = NULL, _1, _2, _3, _4, _5;
        zval value;
        zval this_zv;
        zval *this_ptr = getThis();
        if (EXPECTED(this_ptr)) {
                ZVAL_OBJ(&this_zv, Z_OBJ_P(this_ptr));
                this_ptr = &this_zv;
        } else this_ptr = NULL;

        ZVAL_UNDEF(&value);
        ZVAL_UNDEF(&_1);
        ZVAL_UNDEF(&_2);
        ZVAL_UNDEF(&_3);
        ZVAL_UNDEF(&_4);
        ZVAL_UNDEF(&_5);

        ZEPHIR_MM_GROW();
        zephir_fetch_params(1, 1, 0, &value_param);

        zephir_get_strval(&value, value_param);


        len = zephir_fast_strlen_ev(&value);
        _0 = ZEPHIR_STRING_OFFSET(value, (len - 1));
        ZVAL_LONG(&_1, _0);
        ZEPHIR_CALL_FUNCTION(&_2, "ord", NULL, 69, &_1);
        zephir_check_call_status();
        pad = zephir_get_intval(&_2);
        ZEPHIR_INIT_VAR(&_3);
        ZVAL_LONG(&_1, pad);
        ZEPHIR_CALL_METHOD(&_4, this_ptr, "paddingisvalid", NULL, 0, &_1, &value);
        zephir_check_call_status();
        if (zephir_is_true(&_4)) {
                ZVAL_LONG(&_1, 0);
                ZVAL_LONG(&_5, (len - pad));
                zephir_substr(&_3, &value, 0 , zephir_get_intval(&_5), 0);
        } else {
                ZEPHIR_CPY_WRT(&_3, &value);
        }
        RETURN_CCTOR(_3);

}
```

``` log
In file included from /usr/include/php7/Zend/zend.h:35:0,
                 from /usr/include/php7/main/php.h:35,
                 from /home/mruz/framework/ext/ice/crypt.zep.c:6:
/home/mruz/framework/ext/ice/crypt.zep.c: In function 'zim_Ice_Crypt_stripPadding':
/usr/include/php7/Zend/zend_types.h:519:39: error: invalid type argument of unary '*' (have 'zval')
 #define Z_STRLEN_P(zval_p)   Z_STRLEN(*(zval_p))
                                       ^
/usr/include/php7/Zend/zend_string.h:41:26: note: in definition of macro 'ZSTR_LEN'
 #define ZSTR_LEN(zstr)  (zstr)->len
                          ^
/usr/include/php7/Zend/zend_types.h:518:36: note: in expansion of macro 'Z_STR'
 #define Z_STRLEN(zval)    ZSTR_LEN(Z_STR(zval))
                                    ^
/usr/include/php7/Zend/zend_types.h:519:30: note: in expansion of macro 'Z_STRLEN'
 #define Z_STRLEN_P(zval_p)   Z_STRLEN(*(zval_p))
                              ^
./kernel/operators.h:74:66: note: in expansion of macro 'Z_STRLEN_P'
 #define ZEPHIR_STRING_OFFSET(op1, index) ((index >= 0 && index < Z_STRLEN_P(op1)) ? Z_STRVAL_P(op1)[index] : '\0')
                                                                  ^
/home/mruz/framework/ext/ice/crypt.zep.c:499:7: note: in expansion of macro 'ZEPHIR_STRING_OFFSET'
  _0 = ZEPHIR_STRING_OFFSET(value, (len - 1));
       ^
/usr/include/php7/Zend/zend_types.h:516:39: error: invalid type argument of unary '*' (have 'zval')
 #define Z_STRVAL_P(zval_p)   Z_STRVAL(*(zval_p))
                                       ^
/usr/include/php7/Zend/zend_string.h:40:26: note: in definition of macro 'ZSTR_VAL'
 #define ZSTR_VAL(zstr)  (zstr)->val
                          ^
/usr/include/php7/Zend/zend_types.h:515:36: note: in expansion of macro 'Z_STR'
 #define Z_STRVAL(zval)    ZSTR_VAL(Z_STR(zval))
                                    ^
/usr/include/php7/Zend/zend_types.h:516:30: note: in expansion of macro 'Z_STRVAL'
 #define Z_STRVAL_P(zval_p)   Z_STRVAL(*(zval_p))
                              ^
./kernel/operators.h:74:85: note: in expansion of macro 'Z_STRVAL_P'
 #define ZEPHIR_STRING_OFFSET(op1, index) ((index >= 0 && index < Z_STRLEN_P(op1)) ? Z_STRVAL_P(op1)[index] : '\0')
                                                                                     ^
/home/mruz/framework/ext/ice/crypt.zep.c:499:7: note: in expansion of macro 'ZEPHIR_STRING_OFFSET'
  _0 = ZEPHIR_STRING_OFFSET(value, (len - 1));
       ^
make: *** [ice/crypt.lo] Błąd 1
make: *** Oczekiwanie na niezakończone zadania....
```

**Comment by steffengy** [comment] 2015-11-13 19:25
Thanks for reporting that, could you try again using master?

**Comment by mruz** [comment] 2015-11-14 06:54
It seems that it works, but I have other issuse, `zephir_create_array(&_1$$3` looks strange:

``` c
static zend_object *zephir_init_properties_Ice_Http_Response(zend_class_entry *class_type TSRMLS_DC) {

                zval _1$$3;
        zval _0;
                ZVAL_UNDEF(&_0);
        ZVAL_UNDEF(&_1$$3);

                ZEPHIR_MM_GROW();

        {
                zval local_this_ptr, *this_ptr = &local_this_ptr;
                ZEPHIR_CREATE_OBJECT(this_ptr, class_type);
                zephir_read_property(&_0, this_ptr, SL("messages"), PH_NOISY_CC | PH_READONLY);
                if (Z_TYPE_P(&_0) == IS_NULL) {
                        ZEPHIR_INIT_VAR(&_1$$3);
                        zephir_create_array(&_1$$3, 60, 0 TSRMLS_CC);
                        add_index_stringl(&_1$$3, 100, SL("Continue"));
```

```
/home/travis/build/ice/framework/ext/ice/http/response.zep.c: In function ‘zephir_init_properties_Ice_Http_Response’:
/home/travis/build/ice/framework/ext/ice/http/response.zep.c:1069:4: error: incompatible type for argument 1 of ‘zephir_create_array’
./kernel/array.h:30:22: note: expected ‘struct zval *’ but argument is of type ‘zval’
/home/travis/build/ice/framework/ext/ice/http/response.zep.c: At top level:
```

**Comment by steffengy** [comment] 2015-11-14 09:59
That compiler error makes no sense.
`incompatible type for argument 1: expected ‘struct zval *’ but argument is of type ‘zval’`
argument 1 is `zval _1$$3;` and create_array gets `&_1$$3` (therefor `zval *`),
so this is either the wrong line or there's some magic going on.

**Comment by mruz** [comment] 2015-11-14 12:38
You are right, I probably took the error from https://travis-ci.org/ice/framework/jobs/91078089#L1927 but code from the local machine.

**Comment by mruz** [comment] 2015-11-14 13:40
I added debug to the travis: `cat ext/ice/http/response.zep.c`
code
https://travis-ci.org/ice/framework/jobs/91106235#L1333
error
https://travis-ci.org/ice/framework/jobs/91106235#L3065

 it's `_1$$3`, not `&_1$$3` and why this strange name? before https://github.com/phalcon/zephir/commit/f68701626f413379565b6e1ebc33df23c8e41bcb was just `_1`
https://github.com/ice/framework/blob/dev/ext/ice/http/response.zep.c#L785

**Comment by steffengy** [comment] 2015-11-14 13:48
@mruz 
The name includes the branch if it's not a root-declaration, because of possible variable shadowing,
as specified in the respective PR.

**Comment by mruz** [comment] 2015-11-14 13:51
Do you mean https://github.com/phalcon/zephir/issues/1099?

**Comment by steffengy** [comment] 2015-11-14 13:52
yes

**Comment by mruz** [comment] 2015-11-14 14:00
OK. 
I see difference, on travis error and `_1$$3`, on local no error and `&_1$$3` on PHP 7.0.0RC6 (cli) ( NTS )

**Comment by steffengy** [comment] 2015-11-14 14:24
@mruz 
It might be fixed in the latest master now.

**Comment by mruz** [comment] 2015-11-14 15:35
Also I have problem with `getValue()` and global `_POST`:

``` zep
public function getValue(string name)
    {
        var value;

        // Check if there is a predefined value for it
        if !fetch value, _POST[name] {
            // Check if there is a post value for the item
            if !fetch value, this->values[name] {
                return null;
            }
        }

        return value;
    }
```

PHP7

``` c
PHP_METHOD(Ice_Tag, getValue) {

        zval *name_param = NULL, _POST, value, _0$$3;
        zval name;
                zval this_zv;
        zval *this_ptr = getThis();
        if (EXPECTED(this_ptr)) {
                ZVAL_OBJ(&this_zv, Z_OBJ_P(this_ptr));
                this_ptr = &this_zv;
        } else this_ptr = NULL;

        ZVAL_UNDEF(&name);
        ZVAL_UNDEF(&_POST);
        ZVAL_UNDEF(&value);
        ZVAL_UNDEF(&_0$$3);

        ZEPHIR_MM_GROW();
        zephir_get_global(&_POST, SL("_POST"));
        zephir_fetch_params(1, 1, 0, &name_param);

        zephir_get_strval(&name, name_param);


        ZEPHIR_OBS_VAR(&value);
        if (!(zephir_array_isset_fetch(&value, &_POST, &name, 0 TSRMLS_CC))) {
                ZEPHIR_OBS_NVAR(&value);
                zephir_read_property(&_0$$3, this_ptr, SL("values"), PH_NOISY_CC | PH_READONLY);
                if (!(zephir_array_isset_fetch(&value, &_0$$3, &name, 0 TSRMLS_CC))) {
                        RETURN_MM_NULL();
                }
        }
        RETURN_CCTOR(value);

}
```

PHP5.6

``` c
PHP_METHOD(Ice_Tag, getValue) {

    zval *name_param = NULL, *_POST, *value = NULL, *_0$$3;
    zval *name = NULL;

    ZEPHIR_MM_GROW();
    zephir_get_global(&_POST, SS("_POST") TSRMLS_CC);
    zephir_fetch_params(1, 1, 0, &name_param);

    zephir_get_strval(name, name_param);


    ZEPHIR_OBS_VAR(value);
    if (!(zephir_array_isset_fetch(&value, _POST, name, 0 TSRMLS_CC))) {
        ZEPHIR_OBS_NVAR(value);
        _0$$3 = zephir_fetch_nproperty_this(this_ptr, SL("values"), PH_NOISY_CC);
        if (!(zephir_array_isset_fetch(&value, _0$$3, name, 0 TSRMLS_CC))) {
            RETURN_MM_NULL();
        }
    }
    RETURN_CCTOR(value);

}
```

Looks like `fetch value, _POST[name]` not fetching on PHP7, but fetching from `this->values`.

**Comment by mruz** [comment] 2015-11-20 08:48
PHP7: Strange, #1131 on the local machine and similar code on ice https://travis-ci.org/ice/framework/jobs/91370787 fails, but if I add some reference to _POST before fetch it works, similar to https://github.com/phalcon/zephir/issues/159

``` php
    public function testPost()
    {
        $t = new \Test\FetchTest();

        $_POST = array(
            1 => 'one',
            'two' => 2,
            'three' => array(3)
        );

        // add some reference before fetch, then tests pass
        var_dump($POST);

        $this->assertEquals($t->testFetchPost(1), 'one');
        $this->assertEquals($t->testFetchPost('two'), 2);
        $this->assertEquals($t->testFetchPost('three'), array(3));
    }
```

@steffengy @ovr any ideas?

I see if there is no reference eg. `var_dump($POST);` before and run fetch then the `_POST` is empty

**Comment by steffengy** [comment] 2015-11-20 18:05
@mruz 
So how to get #1131 you submitted to actually fail, so that I can reproduce the issue?

**Comment by mruz** [comment] 2015-11-20 18:20
Could you try to add:

``` zep
/**
 * Fetch statement tests
 */

namespace Ice;

class FetchTest
{

    public function testFetchPost(var b)
    {
        var c;
        if !fetch c, _POST[b] {
            return false;
        }

        return c;
    }
}
```

And run test on PHP7:

``` php
public function testPost()
    {
        $t = new \Ice\FetchTest();

        $_POST = array(
            1 => 'one',
            'two' => 2,
            'three' => array(3)
        );

        $this->assertEquals($t->testFetchPost(1), 'one');
        $this->assertEquals($t->testFetchPost('two'), 2);
        $this->assertEquals($t->testFetchPost('three'), array(3));
    }
```

**Comment by steffengy** [comment] 2015-11-20 18:23
That's exactly the content of #1131 , which passes.
So I don't see how that could fail.

**Comment by mruz** [comment] 2015-11-20 18:32
I know, but it fails on local machine, so could you try to build [ice](https://github.com/ice/framework) on PHP7 and run test TagTest?:

```
cd framework/
./vendor/bin/zephir build
./vendor/bin/phpunit --configuration tests/phpunit.xml tests/TagTest.php
```

**Comment by mruz** [comment] 2015-11-24 11:58
I do not know what more I can do, I did copy `fetchtest.zep` and `FetchTest.php` into ice https://github.com/mruz/framework/commit/b87f5b3606d4950905498353c394d1c73dc93464 and build fails on PHP7 https://travis-ci.org/ice/framework/builds/92916552.

**Comment by mruz** [comment] 2015-11-26 08:11
I reproduced it at https://travis-ci.org/phalcon/zephir/builds/93311637, so @steffengy is this a phpunit issue or what?

**Comment by mruz** [comment] 2015-11-26 12:12
Also

``` zep
protected function dispatchVariableRoute(routeData, uri)
    {
        var data, matches, handler, varName, varNames, vars;
        int i, j;

        let matches = [];

        for data in routeData {
            if !preg_match(data["regex"], uri, matches) {
                continue;
            }

            let j = count(matches),
                handler = data["routeMap"][j][0],
                varNames = data["routeMap"][j][1];

            let vars = [],
                i = 0;

            for varName in varNames {
                let i++,
                    vars[varName] = matches[i];
            }

            return [Router::FOUND, handler, vars];
        }

        return [Router::NOT_FOUND];
    }
```

``` c
PHP_METHOD(Ice_Mvc_Route_Dispatcher_GroupCount, dispatchVariableRoute) {

        int i = 0, j = 0;
        zval *routeData, routeData_sub, *uri, uri_sub, data, matches, handler, varName, varNames, vars, *_0, _10, _1$$3, _2$$3, _3$$3, _4$$3, _5$$3, _6$$3, *_7$$3, _9$$3, _8$$5;
                zval this_zv;
        zval *this_ptr = getThis();
        if (EXPECTED(this_ptr)) {
                ZVAL_OBJ(&this_zv, Z_OBJ_P(this_ptr));
                this_ptr = &this_zv;
        } else this_ptr = NULL;

        ZVAL_UNDEF(&routeData_sub);
        ZVAL_UNDEF(&uri_sub);
        ZVAL_UNDEF(&data);
        ZVAL_UNDEF(&matches);
        ZVAL_UNDEF(&handler);
        ZVAL_UNDEF(&varName);
        ZVAL_UNDEF(&varNames);
        ZVAL_UNDEF(&vars);
        ZVAL_UNDEF(&_10);
        ZVAL_UNDEF(&_1$$3);
        ZVAL_UNDEF(&_2$$3);
        ZVAL_UNDEF(&_3$$3);
        ZVAL_UNDEF(&_4$$3);
        ZVAL_UNDEF(&_5$$3);
        ZVAL_UNDEF(&_6$$3);
        ZVAL_UNDEF(&_9$$3);
        ZVAL_UNDEF(&_8$$5);

        ZEPHIR_MM_GROW();
        zephir_fetch_params(1, 2, 0, &routeData, &uri);

        ZEPHIR_INIT_VAR(&matches);
        array_init(&matches);
        zephir_is_iterable(routeData, 0, "ice/mvc/route/dispatcher/groupcount.zep", 48);
        ZEND_HASH_FOREACH_VAL(Z_ARRVAL_P(routeData), _0)
        {
                ZEPHIR_INIT_NVAR(&data);
                ZVAL_COPY(&data, _0);
                ZEPHIR_INIT_NVAR(&_1$$3);
                zephir_array_fetch_string(&_2$$3, &data, SL("regex"), PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 29 TSRMLS_CC);
                zephir_preg_match(&_1$$3, &_2$$3, uri, &matches, 0, 0 , 0  TSRMLS_CC);
                if (!(zephir_is_true(&_1$$3))) {
                        continue;
                }
                j = zephir_fast_count_int(&matches TSRMLS_CC);
                zephir_array_fetch_string(&_3$$3, &data, SL("routeMap"), PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 34 TSRMLS_CC);
                zephir_array_fetch_long(&_4$$3, &_3$$3, j, PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 34 TSRMLS_CC);
                zephir_array_fetch_long(&handler, &_4$$3, 0, PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 34 TSRMLS_CC);
                zephir_array_fetch_string(&_5$$3, &data, SL("routeMap"), PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 35 TSRMLS_CC);
                zephir_array_fetch_long(&_6$$3, &_5$$3, j, PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 35 TSRMLS_CC);
                zephir_array_fetch_long(&varNames, &_6$$3, 1, PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 35 TSRMLS_CC);
                ZEPHIR_INIT_NVAR(&vars);
                array_init(&vars);
                i = 0;
                zephir_is_iterable(&varNames, 0, "ice/mvc/route/dispatcher/groupcount.zep", 45);
                ZEND_HASH_FOREACH_VAL(Z_ARRVAL_P(&varNames), _7$$3)
                {
                        ZEPHIR_INIT_NVAR(&varName);
                        ZVAL_COPY(&varName, _7$$3);
                        i++;
                        zephir_array_fetch_long(&_8$$5, &matches, i, PH_NOISY | PH_READONLY, "ice/mvc/route/dispatcher/groupcount.zep", 42 TSRMLS_CC);
                        zephir_array_update_zval(&vars, &varName, &_8$$5, PH_COPY | PH_SEPARATE);
                } ZEND_HASH_FOREACH_END();
                ZEPHIR_INIT_NVAR(&varName);
                zephir_create_array(return_value, 3, 0 TSRMLS_CC);
                ZEPHIR_INIT_NVAR(&_9$$3);
                ZVAL_LONG(&_9$$3, 1);
                zephir_array_fast_append(return_value, &_9$$3);
                zephir_array_fast_append(return_value, &handler);
                zephir_array_fast_append(return_value, &vars);
                RETURN_MM();
        } ZEND_HASH_FOREACH_END();
        ZEPHIR_INIT_NVAR(&data);
        zephir_create_array(return_value, 1, 0 TSRMLS_CC);
        ZEPHIR_INIT_VAR(&_10);
        ZVAL_LONG(&_10, 0);
        zephir_array_fast_append(return_value, &_10);
        RETURN_MM();
```

``` sh
(gdb) run ./vendor/bin/phpunit --configuration tests/phpunit.xml.dist --color=always --testsuite=all
Starting program: /usr/bin/php ./vendor/bin/phpunit --configuration tests/phpunit.xml.dist --color=always --testsuite=all
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
PHPUnit 5.0.9 by Sebastian Bergmann and contributors.

.....
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff657eeea in strlen () from /lib64/libc.so.6
(gdb) bt full
#0  0x00007ffff657eeea in strlen () from /lib64/libc.so.6
No symbol table info available.
#1  0x000055555583502b in xbuf_format_converter ()
No symbol table info available.
#2  0x0000555555836400 in vspprintf ()
No symbol table info available.
#3  0x00005555558db797 in zend_error_noreturn ()
No symbol table info available.
#4  0x00007ffff314c4e7 in zephir_array_fetch_long () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#5  0x00007ffff30c9f64 in zim_Ice_Mvc_Route_Dispatcher_GroupCount_dispatchVariableRoute () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#6  0x00007ffff311bf38 in zephir_call_user_function.constprop.106 () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#7  0x00007ffff311cfc6 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#8  0x00007ffff3065649 in zim_Ice_Mvc_Route_Dispatcher_Regex_dispatch () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#9  0x00007ffff311bf38 in zephir_call_user_function.constprop.106 () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#10 0x00007ffff311cfc6 in zephir_call_class_method_aparams () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#11 0x00007ffff30887f9 in zim_Ice_Mvc_Router_handle () from /usr/lib64/php7/extensions/ice.so
No symbol table info available.
#12 0x000055555596bf10 in ZEND_DO_FCALL_SPEC_HANDLER ()
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
```

**Comment by steffengy** [comment] 2015-11-26 14:50
@mruz 
It's probably an edge case that relys on a specific memory layout/code flow,
which makes it hard to reproduce.
I unfortunately currently do not have the time to setup ICE and figure out
what constellation of the code crashes standalone (effectively figuring out the origin of the error, which will probably take some hours)
and then fixing it.
If you can produce a small code sample, which crashes without external dependencies,
I'll gladly take a look at it.
If not, this might take quite a while longer, sorry.

**Comment by mruz** [comment] 2015-11-26 17:06
OK, I'll try to produce the small code sample :wink: 
but how about https://github.com/phalcon/zephir/pull/1131?

**Comment by steffengy** [comment] 2015-11-26 18:14
That's interesting. It seems like it doesn't happen during regular tests, since some code that runs before somehow affects the state whether it crashes (probably some kind of global modification, which prevents the bug to show (probably wrong reference counting, which doesn't appear since the respective value has "enough" references)).

**Comment by mruz** [comment] 2015-12-01 06:36
It happens even if I disable regular tests https://travis-ci.org/phalcon/zephir/builds/94102721:

```
xdebug.dump.POST => no value => no value
```

https://github.com/phalcon/zephir/issues/1126#issuecomment-158327470

**Comment by steffengy** [comment] 2015-12-02 14:02
Fixed that fail you mentioned previously. ( #1131 )
Since this issue contains multiple bug reports and is not very clear,
closing this for now.
If any issue is not fixed, that's mentioned here, please open a separate issue
regarding only that concern.

**Closed as completed by steffengy** 2015-12-02 14:02 UTC
Labels: bug

**Comment by mruz** [comment] 2015-12-03 06:31
OK. Thanks!
