### ISSUE TITLE
namespace with \U warning?

### ISSUE THREAD

**Issue by hellobbq** [zephir-lang/zephir#1117] opened 2015-10-24 09:00 UTC
```
namespace Missing\Utils;
```

compile-errors.log

warning: \U uesd with no following hex digits; treating as '\' followed by identifier [-Wunicode]
ZEPHIR_REGISTER_CLASS(Missing\Utils,File.......)

zephir0.9a-dev php5.6.13

**Comment by steffengy** [comment] 2015-11-06 19:36
Duplicate of #653

**Closed as completed by steffengy** 2015-11-06 19:36 UTC
Labels: minor
