### ISSUE TITLE
BUG: zephir_get_global

### ISSUE THREAD

**Issue by chrysanthemum** [zephir-lang/zephir#1961] opened 2019-10-11 08:35 UTC
> Close all extensions compiled by zephir, including the phaclon extension. Leave only the test extension.

test/globals/server.zep
```
namespace Test\Globals;

class Server
{
    public function f1() -> void
    {
        echo _SERVER["PHP_SELF"];
        this->f2();
        echo _SERVER["PHP_SELF"];
    }
    
    public function f2() -> void
    {
        echo _SERVER["SCRIPT_NAME"];
    }
}
```
manual.php
```
$t = new Test\Globals\Server();
$t->f1();
```

output:
```
/php-src/php-7.2/Zend/zend_hash.c(1968) : ht=0x107e65720 is already destroyed
Assertion failed: (0), function _zend_is_inconsistent, file /php-src/php-7.2/Zend/zend_hash.c, line 64.
```

**Comment by chrysanthemum** [comment] 2019-10-11 09:21
@dreamsxin Could you fix this BUG? I'm afraid I'll make a mistake.

**Comment by sergeyklay** [comment] 2019-10-11 10:29
@chrysanthemum Could you please provide exact PHP version and used Zephir version/commit

**Comment by chrysanthemum** [comment] 2019-10-11 10:38
php:
```
PHP 7.2.22 (cli) (built: Sep 21 2019 13:19:31) ( NTS DEBUG )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.7.2, Copyright (c) 2002-2019, by Derick Rethans
    with Zend OPcache v7.2.22, Copyright (c) 1999-2018, by Zend Technologies
```

zephir:
```
Zephir 0.12.9
git revision number: 4155edf8824ee64a4255be929c48ee108528e8d5
```

operating system：
```
macOS Mojave 10.14.6
```

**Comment by chrysanthemum** [comment] 2019-10-11 10:44
@sergeyklay  After updating the cache, I found that the bug is now gone. This is my mistake.

**Comment by chrysanthemum** [comment] 2019-10-11 10:47
@dreamsxin I got it wrong. There's no bug ：）

**Comment by sergeyklay** [comment] 2019-10-11 10:51
@chrysanthemum Should we close this one?

**Comment by chrysanthemum** [comment] 2019-10-11 10:51
ok

**Comment by chrysanthemum** [comment] 2019-10-11 10:58
@sergeyklay 

Oddly enough, this problem occurred when I closed all the zephir compiled extensions, leaving only the test extension.

If I open the phaclon extension, the bug does not appear.

Do you have this bug? (Close all zephir compiled extensions, leaving only the test extension.)

**Comment by chrysanthemum** [comment] 2019-10-11 11:14
@sergeyklay 
I find another problem, Could you help me?
If I open both zephir compiled extensions. For GDB debugging, program breakpoints did not allow access to the source code in the kernels directory.

**Comment by chrysanthemum** [comment] 2019-10-11 11:25
This strange bug does exist.
@dreamsxin

**Comment by chrysanthemum** [comment] 2019-10-11 11:27
@dreamsxin

**Comment by dreamsxin** [comment] 2019-10-12 04:00
@sergeyklay Revoke that commit https://github.com/phalcon/zephir/commit/ed65fa745931277e62cec3479c4c5b3ed01a3dd5#diff-91d00b5ec72fef64318f760cae59fbda

**Comment by sergeyklay** [comment] 2019-10-12 08:04
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for bug report.

**Comment by sergeyklay** [comment] 2019-10-13 19:43
I'll open this one because changes proposed in #1965 broke our tests. 

For more see:
- https://travis-ci.org/phalcon/zephir/builds/597342289
- https://github.com/phalcon/zephir/pull/1965#issuecomment-541299003
- https://github.com/phalcon/zephir/commit/ed65fa745931277e62cec3479c4c5b3ed01a3dd5#diff-91d00b5ec72fef64318f760cae59fbda

**Comment by dreamsxin** [comment] 2019-10-14 01:12
@sergeyklay 
```zep
public function f1() -> void
{
	echo _SERVER["PHP_SELF"];
	this->f2(); // In zephir_get_global use ZVAL_DUP will separation
	echo _SERVER["PHP_SELF"];
}
```
generate c code:
```c
ZEPHIR_MM_GROW();
zephir_get_global(&_SERVER, SL("_SERVER")); // separation

zephir_array_fetch_string(&_0, &_SERVER, SL("PHP_SELF"), ...);
zend_print_zval(&_0, 0);

ZEPHIR_CALL_METHOD(NULL, this_ptr, "f2", NULL, 0); // separation
zephir_check_call_status();

zephir_array_fetch_string(&_1, &_SERVER, SL("PHP_SELF"), ...); // <-- After separation, the variables here fail. is already destroyed
zend_print_zval(&_1, 0);
ZEPHIR_MM_RESTORE();
```

**Comment by dreamsxin** [comment] 2019-10-14 01:13
@sergeyklay So we need to get global every time.
```c
ZEPHIR_MM_GROW();
zephir_get_global(&_SERVER, SL("_SERVER"));

zephir_array_fetch_string(&_0, &_SERVER, SL("PHP_SELF"), ...);
zend_print_zval(&_0, 0);

ZEPHIR_CALL_METHOD(NULL, this_ptr, "f2", NULL, 0);
zephir_check_call_status();

zephir_get_global(&_SERVER, SL("_SERVER")); // <-- Get global again
zephir_array_fetch_string(&_1, &_SERVER, SL("PHP_SELF"), ...);
zend_print_zval(&_1, 0);
ZEPHIR_MM_RESTORE();
```

**Closed as completed** 2019-10-19 12:50 UTC
Labels: bug

**Comment by mruz** [comment] 2020-03-30 17:04
I have similar issue. If I access to the global variable in zephir and then access with `isset` in php:

```php
if (isset($_POST[$key])) {
    unset($_POST[$key]);
}
```
then I'm getting "502 Bad Gateway":
> [error] 1319#1319: *114 recv() failed (104: Connection reset by peer) while reading response header from upstream

**Comment by sergeyklay** [comment] 2020-03-31 07:43
@mruz Most likely this is a different issue. Could you please create a new issue with code to reproduce?
