### ISSUE TITLE
php7 call self:func() Fatal error :Uncaught RuntimeException: Call to undefined method self::func(), did you mean 'undefined'? in

### ISSUE THREAD

**Issue by tanboname** [zephir-lang/zephir#1372] opened 2016-12-16 03:41 UTC
My environment:
* Linux CentOS 7
* PHP 7.1.0
* Latest Zephir

```zep
test
{
    public static function func() {
    }

    public static function func1() {
        self:func();
    }
}
```

```php
test::func(); // ok
test::func1(); // Call to undefined method self::func()
```

**Comment by sergeyklay** [comment] 2016-12-16 06:37
Could you please provide real Zephir code (not pseudocode)

**Comment by tanboname** [comment] 2016-12-16 11:39
zephir:
```zep
namespace Xy;

class Sdk
{
    public static function func()
    {
    }

    public static function func1()
    {
        self::func();
    }
}
```

php:
```php
Xy\Sdk::func(); // ok
Xy\Sdk::func1(); // error
```

**Comment by dreamsxin** [comment] 2016-12-31 01:11
Can follow this:
```zep
	public static function func() {
	}

	public static function func1() {
		Sdk::func();
	}
```

**Comment by dreamsxin** [comment] 2016-12-31 01:12
@sergeyklay We may be judge, When it's static call auto convert self to current classname.

**Comment by sergeyklay** [comment] 2017-02-28 06:31
@tanboname Could you please provide PHP version and OS?

**Comment by rochael** [comment] 2017-03-01 08:37
I have the same problem, 
MacOS 10.12
php 7.1
lastest zephir
```zep
namespace Utils;

class Test{
	public static function func1 () -> void
	{
		
	}


	public static function fun () -> void
	{
		self::func1();
	}
}
```

```
Utils\Test::fun();
```

```
PHP Fatal error:  Uncaught RuntimeException: Call to undefined method self::func1(), did you mean 'undefined'? in /Volumes/Transcend/Dev/php-ext-project/utils/test.php:
```

**Comment by Jurigag** [comment] 2017-03-17 19:53
I can confirm this is really a bug. Needs to be fixed for phalcon.

Though i think the root of the problem is the same/similar as here - https://github.com/phalcon/zephir/issues/1392

@sergeyklay @andresgutierrez @rafmichalak84 @dreamsxin

**Comment by sergeyklay** [comment] 2017-03-24 22:34
Fixed in the `master` branch.

**Closed as completed by sergeyklay** 2017-03-24 22:34 UTC
Labels: bug
