### ISSUE TITLE
Create instance in loop issue

### ISSUE THREAD

**Issue by navisoft** [zephir-lang/zephir#1673] opened 2018-09-15 19:29 UTC
Example:
<pre>
var instance, className;
for className in ["A", "B"] {
	let instance = new {className}();
	//or
	if className == "A" {
		let instance = new A();
	} else {
		let instance = new B();
	}
	instance->execute();
	instance->another();
}

class A {
	public function execute() {
		echo "A";
	}
	public function another() {
		echo "Aa";
	}
}
class B {
	public function execute() {
		echo "B";
	}
	public function another() {
		echo "Bb";
	}
}
</pre>
Both A and B have the "execute" and "another" method.
Result: The function execute of A instance run twice times.
The function execute of B doesn't runs.

**Comment by danhunsaker** [comment] 2018-10-04 15:33
We only see part of the implementation of `A`, and none of `B`, so it's difficult to say where the problem is being introduced. Can you provide a more complete example?

**Comment by navisoft** [comment] 2018-10-04 15:35
The class B is same the class A. I just updated the question.

**Comment by sergeyklay** [comment] 2018-10-30 07:49
As you can see there is no issue at all #1700 

I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks

**Closed as completed by sergeyklay** 2018-10-30 07:49 UTC
Labels: not a bug
