### ISSUE TITLE
Memory leak - Zephir 0.8 PHP 5.6

### ISSUE THREAD

**Issue by joeyhub** [zephir-lang/zephir#1110] opened 2015-10-05 20:36 UTC
I have found a memory leak in fcall.c line 621:

```
  if (FAILURE == zend_hash_quick_add(zephir_globals_ptr->fcache, fcall_key, fcall_key_len, fcall_key_hash, &cache_entry_temp, sizeof(zephir_fcall_cache_entry*), NULL)) {
```

It passes through zephir_call_class_method_aparams from ZEPHIR_CALL_METHOD to get there.

I am calling a function which is recursive and each time memory allocated goes up by 6536 bytes 2013 bytes of which comes from that.

This appears to happen sporadically when calling a complex web of class methods some of which are recursive.

There is an option to disable the cache but it does not stop this. It only applies to reading the cache.

**Comment by steffengy** [comment] 2015-10-05 20:40
I think its unlikely that there's a memory leak, 
that would just appear in too many situations, which it doesn't.
Maybe it's some case of an edge case.
Also do you have a small code sample to reproduce?
Are you by any change using a debug build (of zephir)?

**Comment by joeyhub** [comment] 2015-10-05 20:43
I'm not 100% sure if this is the cause of the memory leak but it would be great to get rid of it/eliminate it.

There is definitely a memory leak somewhere because I'm running the same deterministic function over and over with the same data with it using 6536 bytes more every time. The same in PHP has a delta of 0 bytes.

Where ever that memory leak is, the memory is getting freed somewhere when PHP shuts down and I can't find it in the framestack either.

I have a little malloc hook that captures all mallocs, reallocs, frees, etc then detects unfreed memory and links it to a stack trace. This memory leak is hiding really well but at least it is picked up by emalloc so there is some hope.

I've tried with out ZEPHIR_RELEASE and the memory leak is on another line.

```
 zephir_fcall_cache_entry *cache_entry_temp = malloc(sizeof(zephir_fcall_cache_entry));
```

The reason I'm skeptical of this in fcall is because it is caching multiple times for a recursive function then persisting that and sticking around after a function exit. I see it repeated twice for what looks like the same stacktrace and not much obvious pattern to it. The mallocs however are not enough to account for more than 10%-20% of the leak.

At this point I'm probably going to have to start knocking blocks out to see what stops or reduces the leak.

**Comment by steffengy** [comment] 2015-10-05 20:49
I can't really do much without a code sample.
I need to understand the circumstances (call types, which code is run) to see what could happen.
Finding the cause is the next step, after reproducing an issue.

Again: Have you built a debug or production build of your extension?

**Comment by joeyhub** [comment] 2015-10-05 20:50
I did generate then make clean and make, php -dextension=pathtobuiltext. Added -g to the Makefile. It's 0.8 from composer.

I don't understand what debug or production build means. There is only builddev as an alternative which doesn't work so I never touched it. Do you mean -DZEPHIR_RELEASE? I have activated that.

It will take a while for me to find a code sample because this is not a trivial algorithm.

**Comment by steffengy** [comment] 2015-10-05 20:56
Your assumption 
`There is an option to disable the cache but it does not stop this. It only applies to reading the cache.`
is btw wrong, it also disables writing the cache (since no fcall hash/cache key is generated)

Most of the time in that situation it's either not a memory leak, or just something you'll have fun searching for. As a tip, focus on getting a small test case, even if that seems impossible, with a high amount of complexity it is certainly more unlikely to understand these kind of problems.
Just comment some stuff out and see if it still leaks, maybe try using USE_ZEND_ALLOC=0 and try to let valgrind find something (which might not work, since disabling the allocator might just free nothing on cleanup - effectively delegating that to the kernel).
Probably using a debug build of PHP (no debug build of the zephir extension though, since that for sure causes memleaks for the sake of debugging) and take a look at the memory leak output from the allocator

(and yeah -DZEPHIR_RELEASE / build -> prod build, builddev -> dev build)

**Comment by joeyhub** [comment] 2015-10-05 21:05
That's subtle/indirect. There is definitely a memleak somewhere. I'll update this when I have pinned it down further.

**Comment by joeyhub** [comment] 2015-10-05 21:21
Pinned it down:

```
public function pipe_delimited_str_to_int_arr(var value)
{
    var i, v;
    let value = explode("|", value);

    for i, v in value
    {
        let value[i] = (int)v;
    }

    return value;
}
```

pipe_delimited_str_to_int_arr("1|2|3")

Doesn't leak if I do:

```
public function pipe_delimited_str_to_int_arr(var value)
{
    var v, out = [];
    let value = explode("|", value);

    for v in value
    {
        let out[] = (int)v;
    }

    return out;
}
```

No more red herrings.

**Comment by joeyhub** [comment] 2015-10-06 14:32
I'm not entirely convinced that there isn't still a memory leak in fcall or somewhere else in the kernel. I'm getting an odd small memory leak. It tends to become more prominent with many more iterations but seems to be something like logn in terms of size increase of the leaks memory each run.

After knocking out bits of code all I can find is that it appears to be related more to how often functions are called than to any particular data.

It might be 24 bits and appears to normalise after a while. Sometimes the delta is negative and sometimes positive (it should always be 0, more is a leak, less means something unusual is happening that defers cleanup).

I've seen some indication that it might normalise over time as though slots are being filled and it happens on a miss but it is hard to confirm this.

It's a shame, apart from the memory leaks and having to manually pass by reference zephir is working fine.

Does zephir come with any functions to dump it's managed memory?

**Comment by steffengy** [comment] 2015-10-06 16:58
Your first code sample doesn't compile.
There are also multiple problems:
`let value = explode("|", str);``should be``var let value = explode("|", str);``
and``for v in str``` doesn't work since str is a string (strings are not iterable)

Is that just a wrong sample, if so please correct it so I can use the exact same code
which triggers it for you.
Also how are you calling the function? (from php/zephir also typewise: static call, object call, ...)

**Comment by joeyhub** [comment] 2015-10-06 17:56
Try it now.

It's an object call on an instance.

**Comment by steffengy** [comment] 2015-10-06 18:06
Thanks,
memory leak seems to come from `zephir_is_iterable(value, &_2, &_1, 1, 0, "", 535);` / separation.
It also seems sensitive to timing.

I think it's the following:
It is a bug with zephir_is_iterable, since you modify the array you're iterating over within
the for loop, which causes the array to be duplicated and not freed or updated after.

So that is just not entirely implemented yet.

**Comment by joeyhub** [comment] 2015-10-06 20:13
That's the two main points dealt with, work around and cause found.

I find that USE_ZEND_ALLOC=0 is particularly useful not only with valgrind but with custom tools as well using mcheck or malloc hooks. debug_zval_dump is useful particularly when playing around with pointers.

The other weird memory leak I had was related to pointers and me not immediately noticing that while in one or two places places zephir separates zvals where it is extremely bad for performance, in other places it preserves references more than you might expect.

This is related to the quirk where in zephir calling array_pop wont COW the array and will change the original array passed up the callstack. PHP will not do that. In zephir with that type of issue you will end up with things referenced higher in the callstack than you expected when that happens.

A useful guard for anyone deliberately culling the COWs is to guard all inputs in a prototype test case with unserialize(serialize($var)).

I hope to have an impressive benchmark soon now the memory leaks appear to be clear.

**Comment by steffengy** [comment] 2015-10-06 20:14
Yeah this unfortunately is just an incomplete implementation,
when the array being iterated on is modified.
Will fix it as soon as I get to it.

**Comment by joeyhub** [comment] 2015-10-06 20:15
No rush :). Dumping some useful tips in case anyone else has similar difficulties.

**Comment by steffengy** [comment] 2015-10-14 09:57
Should be fixed for ZE2.

**Closed as completed** 2015-10-14 09:57 UTC
Labels: bug
